spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://usuario:contrasena@mycluster.1op4x.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

