spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      database: DataAnalisis
      host: localhost
      password: contrasena
      port: 21017
      username: usuario
